# Generated by Django 4.1.7 on 2023-03-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='updates',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='updates',
            name='date',
            field=models.DateField(verbose_name='service date'),
        ),
    ]
