# Generated by Django 4.1.7 on 2023-04-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_car_upgrade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='Guitar',
        ),
        migrations.RenameField(
            model_name='updates',
            old_name='car',
            new_name='guitar',
        ),
        migrations.AlterField(
            model_name='updates',
            name='service',
            field=models.CharField(choices=[('S', 'String change'), ('P', 'Pickup change'), ('T', 'Tone upgrade')], default='S', max_length=1),
        ),
    ]
